# Generated by Django 4.2.1 on 2023-08-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employee_details',
        ),
        migrations.CreateModel(
            name='managerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_information', to='package1.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_recources', to='package1.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_info', to='package1.payroll')),
            ],
        ),
    ]
